max_page_depth: 10
log_level: 0
skip_robots: false
web_settings:
  followlocation: true
  ssl_verifypeer: false
  ssl_verifyhost: 2
  useragent: sitemapper v0.0.0.1
  connecttimeout: 5
  timeout: 5
report_type: text
sitemap_frequency_type: daily
