production:
  max_page_depth: 10
  log_level: 1
  use_robots: true
  web_settings:
    followlocation: true
    ssl_verifypeer: false
    ssl_verifyhost: 2
    useragent: sitemapper v0.0.0.1
    connecttimeout: 5
    timeout: 5
  report_type: text
  sitemap_frequency_type: daily
  scraper_threads: 5
  log:
    file_name: crawl.log
    file_count: 10
    file_size: 10485760
test:
  max_page_depth: 10
  log_level: 0
  use_robots: true
  web_settings:
    followlocation: true
    ssl_verifypeer: false
    ssl_verifyhost: 2
    useragent: sitemapper v0.0.0.1
    connecttimeout: 5
    timeout: 5
  report_type: text
  sitemap_frequency_type: daily
  scraper_threads: 1
  log:
    file_name: crawl-test.log
    file_count: 10
    file_size: 10485760